---
title: "adjusted_OSF_Analyses"
format: html
editor: visual
---

```{r}
#| label: original code lines 1-36

#####
# load packages
library(dplyr)
library(readr)
set.seed(999)
library(scales)
library(bootstrap)
library(knitr)
library(papeR)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache=TRUE)
library(compute.es)
library(tidyr)
library(dplyr)
library(readr)
library(stringr)
library(ggplot2)
library(reshape2)
library(rjson)
library(jsonlite)
library(Matrix)
library(lme4)
library(psych)
library(lmtest)
library(sjPlot)
library(wesanderson)
library(cowplot)
library(magick)
library(ggrepel)

# From Mike Frank
theta <- function(x,xdata,na.rm=T) {mean(xdata[x],na.rm=na.rm)}
ci.low <- function(x,na.rm=T) {
  quantile(bootstrap::bootstrap(1:length(x),1000,theta,x,na.rm=na.rm)$thetastar,.025,na.rm=na.rm)} #  mean(x,na.rm=na.rm) -
ci.high <- function(x,na.rm=T) {
  quantile(bootstrap::bootstrap(1:length(x),1000,theta,x,na.rm=na.rm)$thetastar,.975,na.rm=na.rm) } #-

```

```{r}
#| label: original code lines 98-106
#| echo: false

#######
# Import and process data from Chinese study

chinese_data = read_csv("study4_chinese.csv")

chinese_data$ppt_gender = as.factor(chinese_data$ppt_gender)
contrasts(chinese_data$ppt_gender)[1] <- -1
chinese_data$condition = as.factor(chinese_data$condition)
contrasts(chinese_data$condition)[1] <- -1
 
 
```

```{r}
#| label: reproduction code lines 98-106

library(here)

chinese_data = read_csv(here("R_scripts", "scripts_and_data_original", "Data_Analysis_original", "study4_chinese.csv"))

# the here() function enables us to write relative paths

chinese_data$ppt_gender = as.factor(chinese_data$ppt_gender)
contrasts(chinese_data$ppt_gender)[1] <- -1
chinese_data$condition = as.factor(chinese_data$condition)
contrasts(chinese_data$condition)[1] <- -1
```

```{r}
#| label: original code lines 808-833

######
# Chinese study
data5_overallMeans = chinese_data %>% 
  dplyr::group_by(subject) %>% 
  dplyr::summarise(OverallLikeMe = 100 *  mean(OverallLikeMe)) %>% 
  dplyr::group_by() %>% 
  dplyr::summarise(OverallLikeMe.m = mean(OverallLikeMe), OverallLikeMe.low = ci.low(OverallLikeMe),OverallLikeMe.high = ci.high(OverallLikeMe))

data5_overallMeans

data5_demog_overallMeans = chinese_data %>% 
  dplyr::group_by(ppt_gender,subject) %>% 
  dplyr::summarise(OverallLikeMe = 100 *  mean(OverallLikeMe)) %>% 
  dplyr::group_by(ppt_gender) %>% 
  dplyr::summarise(OverallLikeMe.m = round(mean(OverallLikeMe),1), OverallLikeMe.low = round(ci.low(OverallLikeMe),1),OverallLikeMe.high = round(ci.high(OverallLikeMe),1))

data5_demog_overallMeans


data5_condition_overallMeans = chinese_data %>% 
  dplyr::group_by(condition,subject) %>% 
  dplyr::summarise(OverallLikeMe = 100 *  mean(OverallLikeMe)) %>% 
  dplyr::group_by(condition) %>% 
  dplyr::summarise(OverallLikeMe.m = round(mean(OverallLikeMe),1), OverallLikeMe.low = round(ci.low(OverallLikeMe),1),OverallLikeMe.high = round(ci.high(OverallLikeMe),1))

data5_condition_overallMeans
```

minor differences becaus of the bootstrap

```{r}
{r}
#| label: reproduction code lines 834-848

# M: code to reproduce the results of the paper

overall_like_me <- glmer(OverallLikeMe ~ 1+condition+ (1|subject) + (1|verb), 
                         data = subset(chinese_data), 
                         family = "binomial")

summary(overall_like_me)
```

It was neccessary to write thise code chunk to reproduce the numbers mentioned in the paper

```{r}
#| label: original code lines 834-848


overall_like_me_English <- glmer(OverallLikeMe ~ 1+ (1|subject) + (1|verb), 
                                 data = subset(chinese_data, condition == "english"), 
                                 family = "binomial")

summary(overall_like_me_English)


overall_like_me_Chinese <- glmer(OverallLikeMe ~ 1+ (1|subject) + (1|verb), 
                                 data = subset(chinese_data, condition == "chinese"), 
                                 family = "binomial")

summary(overall_like_me_Chinese)
```

```{r}
#| label: original code lines 849-865

overall_like_me_male <- glmer(OverallLikeMe ~ 1+condition+ (1|subject) + (1+condition|verb), 
                              data = subset(chinese_data, ppt_gender == "man"), 
                              family = "binomial")

summary(overall_like_me_male)


overall_like_me_female <- glmer(OverallLikeMe ~ 1+condition+ (1|subject) + (1+condition|verb), 
                                data = subset(chinese_data, ppt_gender == "woman"), 
                                family = "binomial")

summary(overall_like_me_female)
```

```{r}
#| label: additional code neutral names

# Marie: Neutrale Namen aus Datensatz entfernen und schauen wie hoch der like_me_effect ist 

names_neutral <- chinese_data |> 
    filter(!left_name %in% c("霍普", "贝斯")) |> 
  filter(!right_name %in% c("霍普", "贝斯")) 

left_name_not_neutral <- chinese_data |> 
  filter(left_name %in% c("霍普", "贝斯")) #673

right_name_not_neutral <- chinese_data |> 
  filter(right_name %in% c("霍普", "贝斯"))  #674

# Überprüfung, dass die Namen wirklich raus sind 

names_neutral |> 
  filter(right_name == "贝斯") |> 
  nrow()

names_neutral |> 
  filter(left_name == "贝斯") |> 
  nrow()

names_neutral |> 
  filter(right_name == "霍普") |> 
  nrow()

names_neutral |> 
  filter(left_name == "霍普") |> 
  nrow()

```

```{r}
#| label: additional code neutral names robustness

overall_like_me_Chinese_neutral <- glmer(OverallLikeMe ~ 1+ (1|subject) + (1|verb), 
                                 data = subset(names_neutral, condition == "chinese"), 
                                 family = "binomial")

summary(overall_like_me_Chinese_neutral)

data5_condition_LikeMeGender_neutral_means = names_neutral |> 
  dplyr::group_by(condition,subject) |> 
  dplyr::summarise(LikeMeGender = 100 *  mean(LikeMeGender)) |> 
  dplyr::group_by(condition) |> 
  dplyr::summarise(LikeMeGender.m = round(mean(LikeMeGender),1), LikeMeGender.low = round(ci.low(LikeMeGender),1),LikeMeGender.high = round(ci.high(LikeMeGender),1))

data5_condition_LikeMeGender_neutral_means

data5_condition_LikeMeGender_means = chinese_data |> 
  dplyr::group_by(condition,subject) |> 
  dplyr::summarise(LikeMeGender = 100 *  mean(LikeMeGender)) |> 
  dplyr::group_by(condition) |> 
  dplyr::summarise(LikeMeGender.m = round(mean(LikeMeGender),1), LikeMeGender.low = round(ci.low(LikeMeGender),1),LikeMeGender.high = round(ci.high(LikeMeGender),1))

data5_condition_LikeMeGender_means

data5_overallMeans_neutral = names_neutral %>% 
  dplyr::group_by(subject) %>% 
  dplyr::summarise(OverallLikeMe = 100 *  mean(OverallLikeMe)) %>% 
  dplyr::group_by() %>% 
  dplyr::summarise(OverallLikeMe.m = mean(OverallLikeMe), OverallLikeMe.low = ci.low(OverallLikeMe),OverallLikeMe.high = ci.high(OverallLikeMe))

data5_overallMeans_neutral

data5_demog_overallMeans_neutral = names_neutral %>% 
  dplyr::group_by(ppt_gender,subject) %>% 
  dplyr::summarise(OverallLikeMe = 100 *  mean(OverallLikeMe)) %>% 
  dplyr::group_by(ppt_gender) %>% 
  dplyr::summarise(OverallLikeMe.m = round(mean(OverallLikeMe),1), OverallLikeMe.low = round(ci.low(OverallLikeMe),1),OverallLikeMe.high = round(ci.high(OverallLikeMe),1))

data5_demog_overallMeans_neutral


data5_condition_overallMeans_neutral = names_neutral %>% 
  dplyr::group_by(condition,subject) %>% 
  dplyr::summarise(OverallLikeMe = 100 *  mean(OverallLikeMe)) %>% 
  dplyr::group_by(condition) %>% 
  dplyr::summarise(OverallLikeMe.m = round(mean(OverallLikeMe),1), OverallLikeMe.low = round(ci.low(OverallLikeMe),1),OverallLikeMe.high = round(ci.high(OverallLikeMe),1))

data5_condition_overallMeans_neutral

```

