---
title: "feedback Marie"
author: "Gina Reinhard"
format: html
editor: visual
---

# Background

<!--# Provide background to the reproduction. This might include a description of the original phenomenon/effect, focal studies about the phenomenon, references where theoretical backgrounds are covered in-depth, whether there have already been reproduction attempts and what their outcomes were, what research rests upon the reproducibility of the phenomenon, or why a reproduction on the topic is informative. Discuss the importance of testing the robustness and reliability of findings via alternate methods. -->

In “Cognitive causes of ‘like me’ race and gender biases in human language production”, Brough et al. (2024) <!--# das hier kannst du auch zu den references verlinken, und zwar so:  Brough et al. [-@brough2024] Hast du die Quarto-Datei noch nicht gerendert? Du könntest die durchs Rendern testen, ob die Referenzen funktionieren --> describe how speakers tend to first mention individuals who resemble them or their social group <!--# einfach nur "resemble their social group" reicht -->. The paper claims that this ‘like me’ effect is due to “(...) automatized mechanisms by which humans retrieve words from memory to produce sentences” ([@brough2024], p. 1706). They demonstrate that the names of individuals who are more similar to the participants are more accessible to the participants.

The focus of the paper is the influence of gender and race. The effect was observed in four different studies. Testing both English and Chinese L1 and L2 speakers <!--# L1 and L2 speakers bezieht sich nur auf English und nicht auf Chinesisch, müsste klarer formuliert werden -->, the authors claim that the ‘like me’ effect is independent of demographic background <!--# nicht demographic background, sondern Muttersprache. Bzw. bezieht "demographic background" race und gender mit ein, das wird in dem Satz nicht klar bzw. passt es alternativ besser an das Ende des ganzen Absatzes oder Anfang des nächsten Absatzes-->. In Studies 1–3, participants had to learn the names of eight persons shown on photographs, who were either Black or white and male or female. They then had to describe events in which two of the persons, differing in either gender or race, engaged in symmetrical interactions. The aim of the studies was to measure “the degree to which participants framed their descriptions in ways that highlighted their own social group, by beginning their sentences with the name of the person who matched them in gender or in race” ([@brough2024], p. 1707). 

Although the overall ‘like me’ effect was small, with mean values of around 55% ([@brough2024]p. 1711), the authors conclude that the observed social bias is important. They suggest that the effect is independent of language, linguistic construction, and social group, although Bough et al. (2024: 1711) <!--# hier z.B. auch möglich: Brough et al. [-@brough2024: 1711], du könntest die Referenzen im ganzen article noch so anpassen --> acknowledge that the first conclusion is based on just two languages (English and Chinese). According to the authors, “the fact that the like me effect was invariant across constructions suggests that it is driven by accessibility and incrementality, rather than by evaluation” ([@brough2024]p.1711). They claim that “a core conclusion from the present studies is that the incremental and accessibility-driven language system that allows speakers to produce language that is fluent also leads them to produce language that is biased” ([@brough2024e] p. 1711). Other researchers hope that the large phenomenon of implicit biases will be studied more in the future [@axt2025] or that counterstereotypical AI can be used to cause a shift to no longer represent certain group members based on stereotypical information which is stored in the memory <!--# das verstehe ich nicht ganz, welches memory? -->[@hermann2025].

The recent study "Exploration of Animacy in the "Like-Me" Effect" [@halpern] aimed at replicating the original study by Brough et al. (2024) "to see if the Like-Me Effect would occur on the axis of gender, if the characters presented were animated." [@halpern]. This study failed to replicate a significant overall "Like-Me" effect, but found a significant effect of Gender. Male participants were more likely to produce a "Like-Me" bias than female participants [@halperna]. Moreover they found that men were more likely to produce a "Like-Me" bias in the animated condition whereas there was not a difference between women and men in the Mixed condition to produce a "Like-Me" response[@halpernb]. One limitation of the replication is, that the sample was not diverse <!--# not diverse in terms of what? age+education? oder auch gender? --> and consisted of 32 students who were all registered in the psychology department at Florida State University [@halperna].

## Motivation for the present study

To our knowledge the study has not been reproduced. The original study provides open access to their data, stimuli and R scripts as well as to their preregistrations and reviews.

Moreover, as we did have access to the preregistrations, we noticed that the reported models in the paper for Study 2 differ considerably from the models that were preregistered <!--#  inwiefern? Falls das für Study 2 nicht weiter ausgeführt wird, würde ich hier einen Punkt setzen und den nächsten Satz mit "moreover" o.ä. anfangen, da es sonst schwer zu verstehen ist -->and that the preregistered models for Study 3 differ from the models reported in the article in that they include gender and race as fixed effects. Therefore we performed robustness checks by computing the preregistered models using the provided data.

In Study 4, the authors indicate that the observed ‘like me’ gender effects may be smaller in Chinese because of including two possibly gender neutral chinese names ( 霍普 \[Hope\] and 贝斯 \]Beth\]). Therefore we decided to rerun the analysis for Study 4 with a subset of the data that excluded these two neutral names. We noticed that the main claim made on the basis of these data relies on a GLMM in which the ‘like me’ effect is modelled as a numeric predictor ranging from -1 to 0. However, this variable only has three possible values that, somewhat counterintuitively, correspond to the following: 

-   -1 = highest me-likeness (i.e. both race and gender match participant demographic)

-   0 (only race or gender matches participant demographic)

-   1 = lowest me-likeness (neither race nor gender match participant demographic

We believe that this variable would be better modelled as an ordinal categorical variable, hence we reran the reported model with the independent variable modelled as an ordered factor.
