---
title: "A comment on “Cognitive causes of ‘like me’ race and gender biases in human language production” (Brough et al. 2024)"
author: ADD NAMES
date: last-modified
execute: 
  warning: false
format: 
  pdf:
    number-sections: true
    message: false    
editor: visual
bibliography: references.bib
---

```{r echo=FALSE}
#install.packages("knitcitations") 
library(knitcitations)
#install.packages("rmarkdown")
library(rmarkdown)
```

This is a [template](https://osf.io/brxtd/files/wyxd3) that you can use to report results from reproduction studies in the social sciences. A reproduction is the repeated analysis of a published finding using the same data. Please ensure that the study you intend to report adheres to the following criteria.

**Reproduction is assigned to one original study that tested at least one identical hypothesis.**

- [ ] Reproduction is not “only” a numerical reproduction of the original report’s results but has some added feature (e.g., different software, code, robustness analyses).

- [ ] No original authors have co-authored the reproduction: While involvement of the original authors in the form of consultancy is accepted, *Replication Research* does not publish reproductions co-authored by any of the original author.

- [ ] A dataset from the original study is analysed. If *different* data is used, please use the template for replication studies instead: <https://osf.io/3jgxd>.

- [ ] This is the most recent version of this document (check here: <https://osf.io/wyxd3>).

To complete this template, please provide the information underneath each heading for your study. You need to use a single template for each reproduction study that you want to report. The paper has four main sections: (1) Background; (2) Methods; (3) Results; (4) Evaluation. This template is heavily based on the data paper template by @evans_journal_2024. Some parts (e.g., reproduction closeness) are based on suggestions by @brandt_replication_2014. Before publishing your report, please delete the instructions that are written in blue.

Completed reports can be submitted to the non-peer reviewed [Zenodo Replication Research Community](https://zenodo.org/communities/r2/) or to the peer reviewed journal [Replication Research](https://replicationresearch.org).

## License {.unnumbered}

If you are using this template [@roseler_handbook_2025] or parts of this template to structure your report, please cite it:

Röseler, L., Hein, M., & Oppong Boakye, P. (2025). StaRT Reports.\
https://doi.org/10.17605/OSF.IO/BRXTD

{{< pagebreak >}}

## Title {.unnumbered}

<!--# Describe what phenomenon or finding you have attempted to reproduce (e.g., “Reproduction of Anchoring Effects using River Lengths”). -->

## Abstract {.unnumbered}

<!--# Describe the type of the reproduction, that is, whether it is an assessment of computational reproducibility, a recreation of the script, whether partly different data are being used, and whether robustness checks are planned (see for example @ankel-peters_protocol_2025). The type of reproduction should be justified by the goals of this project (e.g., to test for a false-positive or examine generalizability). -->

The original study by Brough  et  al. (2024) investigates how social biases may influence automatic word retrieval mechanisms during sentence production. Across four experiments, the authors observe significant ‘like me’ effects, whereby speakers preferentially mention people who share their own race and gender before naming out‑group members (β = 0.16, SE = 0.02, z = 7.7, p \< 0.001). Psycholinguistic manipulations show that the effect does not vary across grammatical constructions (χ²(2) = 0.65, p = 0.721).

We conducted a computational reproduction using the authors’ original raw data and R scripts, supplemented by reconstruction of some missing scripts/steps, and performed multiple robustness checks (alternative model specifications, alternative exclusion criteria, etc.). Full reproduction of the original statistics was achieved for Studies  1–3. The statistical results of Study 4 were also reproduced except for a sign error.

We conclude that the findings reported in Brough et al. (2024) are computationally reproducible using the authors’ scripts with some minor adjustments and additions. We also found them to be robust to our modifications. To facilitate future repetitive research and cumulative endeavours, we recommend that multi‑study papers provide detailed README files.

(172 words)

## Keywords {.unnumbered}

like me biases; human language production;

<!--# Provide a maximum of 5 keywords to help quickly communicate the research foci of the reproduction, separated by a semicolon. -->

{{< pagebreak >}}

# Background

<!--# Provide background to the reproduction. This might include a description of the original phenomenon/effect, focal studies about the phenomenon, references where theoretical backgrounds are covered in-depth, whether there have already been reproduction attempts and what their outcomes were, what research rests upon the reproducibility of the phenomenon, or why a reproduction on the topic is informative. Discuss the importance of testing the robustness and reliability of findings via alternate methods. -->

## Original and Reproduction Study References

<!--# Provide references with DOIs for the original and reproduction study that adhere to your field’s standard (e.g., APA citation style). If the reproduction study has not yet been published, provide a link to a repository where results and materials are stored (e.g., Zenodo.org, OSF.io). -->

|              | Reference with DOI | Study number |
|--------------|--------------------|--------------|
| Original     |                    |              |
| Study number |                    |              |

## Reproduced Study, Hypothesis, and Findings

<!--# If the original article reported multiple studies, hypotheses, or effects (e.g., for different items or sub-samples) please describe which of these you reproduced and provide its number in the original paper (e.g., 1 or 2A). -->

# Methods

<!--# Describe the methods used for data collection including all sub-headings below as detailed as possible. There is no word limit to this section; we are looking for a carefully detailed account of the data collection methods with sufficient detail to allow further reproductions and meaningful secondary use of the data. -->

## Reproduction type

# **2. Computational Reproducibility**

<!--# Describe the type of the reproduction, that is, whether it is an assessment of computational reproducibility, a recreation of the script, whether partly different data are being used, and whether robustness checks are planned (see for example @ankel-peters_protocol_2025). The type of reproduction should be justified by the goals of this project (e.g., to test for a false-positive or examine generalizability). -->

The original data and code were made available on the OSF (<https://osf.io/87vew/overview>). The repository includes raw and analysis data, as well as cleaning and analysis code in R. As the analysed paper comprises a multitude of studies, we found the total number of subdirectories and files overwhelming. The absence of a ReadMe file made navigating the data packages challenging. 

In the preprocessing scripts for Studies 1–3 (`Process_Study1_Data.R`, `Process_Study2_Data.R`, `Process_Study3_Data.R`) the authors mention that, due to a technical issue involving an unbacked-up computer, the authors no longer have access to all the initial raw data for these studies. However, they provide full access to data files, which have apparently only been hand-corrected for minor spelling mistakes (e.g. 'Rth' instead of 'Ruth'). We therefore classified these files as “raw data provided”. \

|                                 |           |             |        |
|---------------------------------|-----------|-------------|--------|
|                                 | **Fully** | **Partial** | **No** |
| Raw data provided               | x         |             |        |
| Cleaning code provided          | x         |             |        |
| Analysis data provided          | x         |             |        |
| Analysis code provided          | x         |             |        |
| Reproducible from raw data      |           | x           |        |
| Reproducible from analysis data |           | x           |        |

We were able to computationally reproduce the results of Studies 1-3 with the code provided by the authors. The only noticeable difference was a slight change in the numbers of the 95% bootstrapped confidence intervals with a maximal difference of ±0.2, which we believe is due to the way random seeds were set in the R scripts. The function set.seed(), by default, in R only applies to the next operation that involves randomisation. The authors only set a seed at the top of the manuscript and not every time randomisation was intended . <!--# ELF: If I remember right, this was because the authors set a seed at the top of a script and assumed it would apply to all randomised processes but, by default, set.seed() in R only applies to the next operation that involves randomisation. Please check and elaborate here to make clear why the seeds did not work as intended. M: I did check it, it was only once at the very beggining of the scirpt-->

Concerning Study 4, we were unable to fully reproduce two processed data files (`study5_chinese.csv` and `data5_chinese.csv`) from the raw data using the corresponding preprocessing script (`Data Preprocessing/Chinese Study/Process_Chinese_Data.R`). The script returned an error because the column `TrialType` does not exist. We noted that the raw data does include a column entitled `trial_type` which, however, only contains a single unique value: “survey_text”. By contrast, the `Trial_Type` variable contained in the processed data file uploaded by the authors, `data5_chinese.csv`, has two levels, differentiating between “RaceTrial” and “GenderTrial”. We were unable to reproduce this variable on the basis of the raw data, but all other variables were successfully reproduced. For Study 4, we therefore had to use the `study5_chinese.csv` and `data5_chinese.csv` processed data files provided by the authors to reproduce the statistical analyses based on these data. 

Moreover, we were unable to reproduce the median time taken to complete inputting the “critical sentence”, which according to the paper is 9.5 s in the English condition and 8.3 s in the Chinese condition ([@brough2024], p. 1713 ). It was not clear to us what exactly was meant by “critical sentence” and how these could be identified in the datasets. We also observed a minor difference in the final sample size for women in the English condition for Study 4. The paper refers to 28 women ([@brough2024], p.1713), but after excluding those with slow RTs, the script `Process_Chinese_Data.R` contains a table with \`condition\`, \`ppt_gender\`, \`list\` and \`n\` in which only 27 English women are listed.

We were able to reproduce the results of the ‘like me’ effect reported as part of Study 4. However, we were unable to locate the code necessary to reproduce some of the values reported in the paper and therefore had to write the code ourselves to check these numbers. This was the case for size of the overall ‘like me’ effect, reported as β = 0.18 (0.04), z = 5.0, P \< 0.001, which we successfully reproduced, as well as the claim that “the size of the effect did not significantly differ depending on the language used” ([@brough2024a], p. 1710), for which we reproduced the same statistics as in the original study apart from one value: we obtained a negative number for the *z*-value (*z* = -1.299) whereas, in the paper, a positive *z*-value (*z* = 1.3) is reported ([@brough2024a], p. 1710). This sign error is likely to be a typographical error and does not change the claims made in the paper. As with Studies 1-3, we also observed minor differences in the values of the 95% bootstrapped confidence intervals. 

For the Empathy Rating Study, the preprocessing script (`Data Preprocessing /EmpathyStudy/process_data.R`) filtered participants, but did not create the processed dataset used in subsequent analyses. Consequently, it was originally unclear to us whether the data used in the analysis script (`Data Analysis/empathy_study_data.csv`) matches the output of the preprocessing steps. However, we were eventually able to successfully recreate the dataframe used by the original authors, based on an modified version of their preprocessing script, the information provided in the preregistration (<https://aspredicted.org/7698v.pdf>), and the raw data provided by the authors (`Data Preprocessing /EmpathyStudy/full_empathy_data.csv`).

The Agency Rating Study is based on two separate preregistered studies and data collections (one for transitive and one for conjoint constructions), both carried out on Prolific. We were able to successfully reproduce the combined processed dataset from the raw Prolific data using the preprocessing script provided (`Data Preprossessing/Rating Study/process_rating_data.R`). 

We were also able to successfully reproduce all of the plots presented in the paper (see `OSF_Analyses_reproduction.qmd`).

On p. 1709, the authors [@brough2024b] write:

> As Fig. 2a shows, the sizes of the like me effects varied only minimally across the grammatical constructions that we had tested (χ2(2) = 0.65, P = 0.721). Rated agency and rated identification, by contrast, strongly varied based upon the grammatical constructions (both χ2(2) \> 200, P \< 0.001) and clearly dissociated from one another. <!--# ELF: Make sure you correctly format this quote, adding non-breaking spaces whether necessary and the subscript numbers, italics, etc. M: did double check it with the original paper -->

We were unable to reproduce the first chi-square value. Our understanding of the code is that the “Test of grammar” section (from line 1022 of the authors' `OSF_Analyses.R` script) best corresponds to this analysis. This test also returns a non-significant *p*-value (0.4886), but a chi-square value of 2.4272. We were able to reproduce the second chi-square value in the quoted paragraph above as 201.99 for the rated agency (transitive and conjoint sentences) and 820.96 for the rated identification (referred to in the code/data as the Empathy Rating Study). Both correspond to *p*-values that are, indeed, \< 0.001.

We successfully recreated the processed dataset necessary for the analysis of the memory naming task (`studies1_2_3_memory.csv`) based on the raw data using the script `overal_memory_data_processing.R`; however, we noted that this script – which is over 1000 lines long – appears to repeat many of the data processing steps completed in earlier data processing scripts. This is particularly true of the removal of trials and participants according to the exclusion criteria; the latter of which is achieved by filtering out hard-coded participant IDs, which were presumably identified via the visual analysis of the tables produced in the script. It also includes some interactive elements (where the user needs to change a variable multiple times to check various subsets of the data) and many repeated code chunks within the script, too, making it difficult to check for consistency. In spite of the presence of comments in the code, it is difficult to follow the logic of the various data wrangling steps. As delivered, this preprocessing script <!--# ELF: Or is this a data processing script? M: yes, it is in the folder Data_Preprocessing_original --> is not reproducible.

The main result of the memory naming experiment could be reproduced (β = 0.02 (0.005), t(642) = 4.5, p \< 0.001). The mean reaction times reported on pp. 1709–1710 could all be reproduced. The bootstrapped confidence intervals differed slightly, but this is not surprising as no random seed was set in the `overall_memory_analysis.R` script.

For the Multi-Study analysis, which combines the data across Studies 1 through 3, the Methods section ([@brough2024b]p. 1712ff.), describes what is being investigated in that part of the paper: 

> We analysed the effect of syntax across the first three studies using a regression of the form LikeMe \~ 1 + Grammatical Frame + (1\|subject) + (1\|event).
>
> \[...\]
>
> The main omnibus analyses used mixed-effects regressions of the form LikeMe \~ 1 + Participant Gender × Participant Race + (1\|subject) + (1 + Participant Gender × Participant Race\|event). Predictors were contrast coded, and separate models were fit to the race and gender trials. The analysis of trial type (using data from all four production studies) had the form LikeMe \~ 1 + Trial Type \[Gender versus Race-focused\] + (1 + Trial Type\|subject) + (1 + Trial Type\|event)” (p. 1713f.).

These regression models can be found in the code provided by the auhors `R_scipts/scripts_and_data_original/Data_Analysis_Original/OSF_Analyses.r` ( <!--# ELF: Add file path plus name here, M: did add it -->) and match the descriptions in the paper. We successfully reproduced the results of these analyses.

## Original and Reproduction Study Features

<!--# Provide a clear overview of the hypothesis, original study, and reproduction study. Describe all differences between the studies using the table below, highlighting any changes or enhancements in the analysis procedures from the original work. -->

**Table 1** *Differences Between the Original and the Reproduction Study*

| Study Feature | Original Study | Reproduction Study | Justification and Possible Effect on Interpretability |
|------------------|------------------|------------------|------------------|
| Software and versions |  |  |  |
| Functions |  |  |  |
| ... | ... | ... | \[press Tab here to add new rows\] |

## Involvement of Original Authors

<!--# Describe whether you have contacted any of the original authors, what their recommendations were, and all materials that they provided you with. Original authors cannot be co-authors on the reproduction study if you plan to submit it to Replication Research.  -->

Did original authors provide:

- Code/data? → Permitted (non-authorship) 

- Analysis input? → Permitted (non-authorship) 

- Draft revisions? → NOT permitted (co-authorship)

{{< pagebreak >}}

## Preregistration

<!--# If applicable, provide the links for the original and reproduction study’s preregistration. @ankel-peters_protocol_2025 recommend preregistering robustness checks after gaining familiarity with data and code but before implementing new analyses -->

| Study        | Preregistration link |
|--------------|----------------------|
| Original     |                      |
| Study number |                      |

## Availability of Materials

<!--# Provide an overview of all materials (raw and processed data, code), where to find them (e.g., openly accessible, shared upon request, accessible via a specific institution, access protocol), and, if applicable, what license they are under. -->

# Results

<!--# Describe potential changes that had to be made so that the reproduction could work (e.g., choosing specific software versions, fixing errors or typos, switching to other methods). Use the sections below and table to report findings from the original and reproduction study. -->

## Original key statistical result and interpretation

| Claim | Key results and interpretation | Reproduction result |
|------------------------|------------------------|------------------------|
| Please provide the original |  |  |
| authors’ claim and page number | Key statistical result from the original report |  |
| Correlations between variables of interest | Table 1 | Table 2 |
| Relationship between variable x, y, and z | Figure 4 | Figure 2 |

## Comparison of Results Between Original Study and Reproduction

<!--# Report original and reproduction results and evaluate their similarity. Comment on the impact of using different analytical methods on the original findings (“robustness reproduction”, @ankel-peters_protocol_2025). Discuss whether the conclusions of the original study are upheld or reconsidered. -->

## Further results

<!--# If you conducted any sort of robustness checks, extensions or auxiliary/exploratory analyses, you can report them here. Include a justification for each robustness check. Beyond individual checks, you can also include specification curves. -->

## Dataset and Materials link

<!--# Please include a permanent identifier, such as a DOI, that points to the online location of the dataset and all used materials. If this resource has already been accessible, a new DOI is not required. -->

## Object/file name

<!--# Please note the exact name of the dataset used to arrive at the reproduction results (e.g., data.csv). -->

## Limits to sharing

<!--# If the data is currently under embargo, please give the length and date at which the data will be made open. Otherwise, please note any potential barriers to full sharing of the data e.g., if it contains identifying information, how gatekeeping is maintained. Please note that you will need to provide full access to the project contributors and potential reviewers for the sake of transparency, in full confidentiality. -->

## FAIR data/Codebook

- [ ] Data deposited in certified repository (e.g., OSF, Zenodo)

- [ ] Dataset has persistent identifier (DOI)

- [ ] Code shared with open license (e.g., MIT, GPL)

- [ ] Codebook includes:

  - [ ] Variable names Description
  - [ ] Valid ranges
  - [ ] Missing codes

- [ ] Metadata uses standard schema (e.g., Datacite, CodeMeta)

- [ ] File formats are non-proprietary (e.g., .csv, .txt, .R)

## Deviations from the Preregistration

<!--# If applicable, discuss for each deviation from the preregistration (1) how you deviated, (2) why you did so, and (3) how this might affect the results. Please also list cases where the preregistration was unspecific and you had to make decisions after data collection (e.g., no preregistered exclusion criterion, hypothesis test was not specified as one- vs. two-tailed). If you did not deviate in any way, write “We did not deviate from the preregistration in any way.” In cases where two different sets of results could be obtained (e.g., one- and two-tailed test), please describe the results for both cases. -->

| Description of Deviation | Reason for Deviation | Influence on the Results |
|--------------------------|----------------------|--------------------------|
| ...                      | ...                  | ...                      |
|                          |                      |                          |

## FORRT Replication Database (FReD) Entry

Please disclose whether your results have already been entered into the replication database. To check it, you can enter the DOI of the target study here: <https://forrt.org/apps/fred_annotator.html>. If they are, we will link this report to the entry. If they are not, we invite you to enter them in the spreadsheet or in case of a low number of replication effects here: <https://docs.google.com/forms/d/e/1FAIpQLSeMCwdtP0TPgL55stniuyyTxnNwyC34mO4VUuLcQwYrLI89sQ/viewform>.

# Evaluation

<!--# Please describe everything you learned from your reproduction. This may include acknowledging strengths and limitations of the original or reproduction study or materials, recommendations for future research on the topic, or how the findings are related to other studies in the area or previous reproduction studies. The evaluation should further cover computational reproducibility, robustness, and optionally external validity. -->

## Feedback from the original study’s authors (optional)

You may reach out to the original authors. In this case, we recommend adhering to the “golden rule of reproductions: treat others and their work, as you would like others to treat you and your work!” [@berkeleyinitiativefortransparencyinthesocialsciencesteam2020]. For email templates, see the ACRE guide: <https://bitss.github.io/ACRE/comunications.html#for-reproducers-contacting-the-authors-of-the-original-study>

Original authors were contacted on \[date\].\
Their response:\

- [ ] Comments appended

- [ ] Declined to comment

- [ ] No response after 4 weeks.

If no response, editors may independently solicit feedback.

## Limitations and Recommendations for Future Replications

<!--# Discuss your study’s limitations (e.g., in terms of validity) and make recommendations for what future studies related to this topic should consider. -->

## Brief Evaluation

<!--# Describe in up to two sentences the level of reproducibility. If you use a specific metric such as reproducibility score, describe that metric. -->

{{< pagebreak >}}

Other information required for submission, not for review

# Contribution Statement {.unnumbered}

<!--# Please list all contributions towards this manuscript, including the contributions of all individuals who helped to conduct the data (who may also not be an author of a potential publication regarding this study), including their roles and affiliations at the time of data collection. We explicitly encourage you to include students or research assistants if they were involved in designing or conducting the study. -->

# Ethical Statement {.unnumbered}

<!--# Please provide an appropriate ethical statement if your work involves live subjects (human or animal). For example, the research should have been conducted in accordance with the Declaration of Helsinki and local requirements. -->

# Acknowledgements {.unnumbered}

Please add any relevant acknowledgements to anyone else who supported the project in which the data was collected, but did not work directly on the data itself.

# Conflicts of interest {.unnumbered}

are defined as “when authors, reviewers, or editors have interests that are not fully apparent and that may influence their judgments on what is published. They have been described as those which, when revealed later, would make a reasonable reader feel misled or deceived” (COPE, 2003). Please note any potential conflict of interests, including but not limited to direct or indirect financial gains or non-financial implications. If you have no conflicts to declare, please state explicitly: “The author(s) declare no conflict of interest associated with the publication of this manuscript.

# Funding statement {.unnumbered}

If the data, or the project from which it came, required funding, please provide clear detail of this here. For example, if funded by a research council this would include the year of successful receipt of funding, the name of the funding council, and the grant number.

{{< pagebreak >}}

# References {.unnumbered}

Please enter references (preferably in the APA style) and include a DOI where available.
